# Generated by Django 5.1.3 on 2024-11-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the about section', max_length=255)),
                ('description', models.TextField(help_text='Detailed description')),
                ('mission', models.TextField(blank=True, help_text='Mission statement', null=True)),
                ('vision', models.TextField(blank=True, help_text='Vision statement', null=True)),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address', null=True)),
                ('website_url', models.URLField(blank=True, help_text='Official website link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the record was last updated')),
            ],
        ),
    ]
