# Generated by Django 5.1.3 on 2024-11-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the person', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20, null=True)),
                ('message', models.TextField(help_text='Message the user wants to send')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the contact was created')),
            ],
        ),
    ]
