# Generated by Django 5.1.3 on 2024-11-28 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255)),
                ('delivery_zones', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('wallet_address', models.CharField(max_length=255, unique=True)),
                ('certification_status', models.BooleanField(default=True)),
                ('number_of_deliveries', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('customUser.user',),
        ),
    ]
