# Generated by Django 5.1.3 on 2024-11-28 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor', '0001_initial'),
        ('product', '0001_initial'),
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('SALE', 'Sale'), ('LEASE', 'Lease'), ('SERVICE', 'Service Agreement'), ('PARTNERSHIP', 'Partnership Agreement'), ('PURCHASE_ORDER', 'Purchase Order'), ('SUPPLY_AGREEMENT', 'Supply Agreement'), ('DISTRIBUTION', 'Distribution Agreement'), ('CONTRACT_FARMING', 'Contract Farming'), ('FRANCHISE', 'Franchise Agreement'), ('JOINT_VENTURE', 'Joint Venture Agreement'), ('CONSULTING', 'Consulting Agreement'), ('COOPERATIVE', 'Cooperative Agreement'), ('MEMORANDUM', 'Memorandum of Understanding'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('terms_and_conditions', models.TextField()),
                ('payment_terms', models.TextField()),
                ('valid_until', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_contracts', to='distributor.distributor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_contracts', to='retailer.retailer')),
            ],
        ),
    ]
