# Generated by Django 5.1.3 on 2024-11-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartContract', '0002_alter_smartcontract_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartcontract',
            old_name='customer_approved',
            new_name='retailer_approved',
        ),
    ]
