# Generated by Django 5.1.3 on 2024-11-28 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('GRAIN', 'Grain'), ('DAIRY', 'Dairy'), ('MEAT', 'Meat'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('quality_certifications', models.BooleanField(default=False)),
                ('harvest_date', models.DateField()),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(max_length=255)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farmer.farmer')),
            ],
        ),
    ]
